apiVersion: v1
appVersion: 3.7.4
description: Highly available RabbitMQ cluster, the open source message broker software
  that implements the Advanced Message Queuing Protocol (AMQP).
home: https://www.rabbitmq.com
icon: https://raw.githubusercontent.com/ppc64le/charts/master/logo/rabbitmq.png?sanitize=true
keywords:
- rabbitmq
- message queue
- AMQP
- AMQPS
- MQTT
- STOMP
- Limited
- ppc64le
- Tools
- ICP
maintainers:
- email: smohite@us.ibm.com
  name: IBM ISV Team
name: ibm-rabbitmq-ha
sources:
- https://github.com/rabbitmq/rabbitmq
- https://github.com/docker-library/rabbitmq
tillerVersion: '>=2.7.2'
version: 1.6.3
