appVersion: 1.5.6
description: Free & open source, high-performance, distributed memory object caching
  system.
engine: gotpl
home: http://memcached.org/
icon: https://upload.wikimedia.org/wikipedia/en/thumb/2/27/Memcached.svg/1024px-Memcached.svg.png
keywords:
- memcached
- cache
maintainers:
- email: smohite@us.ibm.com (The original work for this helm chart is done by Kubernetes
    Charts Greg Taylor(gtaylor@gc-taylor.com))
  name: IBM ISV Team
name: memcached
sources:
- https://github.com/docker-library/memcached
version: 2.1.1
