apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "kaazinggateway.fullname" . }}
  labels:
    app: {{ template "kaazinggateway.name" . }}
    chart: {{ template "kaazinggateway.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "kaazinggateway.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "kaazinggateway.name" . }}
        release: {{ .Release.Name }}
        chart: {{ template "kaazinggateway.chart" . }}
        heritage: {{ .Release.Service }}
    spec:
      hostname: kaazinggateway
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
           - name: MY_POD_NAME
             valueFrom:
               fieldRef:
                 fieldPath: metadata.name  
           - name: GATEWAY_OPTS
             value: {{ "-Dgateway.hostname=kaazinggateway -Xmx512m -Djava.security.egd=file:/dev/urandom" }}
          ports:
            - name: http
              containerPort: 8000
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
{{- if .Values.node }}
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: beta.kubernetes.io/arch
                operator: In
                values:
                - {{ .Values.node }}
{{- end }}

